"""
Generated from the exported Magicline studio list.

ALL_STUDIOS contains every entry from the export.
STUDIOS contains only entries with a usable public studio URL and is used by the tracker.
"""

ALL_STUDIOS = [{'id': 1815762810, 'slug': 'ai-fitness-ahlen-city', 'name': 'Ai Fitness Ahlen City', 'city': 'Ahlen', 'url': None},
 {'id': 1815835780, 'slug': 'ai-fitness-ahlen-sud', 'name': 'Ai Fitness Ahlen Süd', 'city': 'Ahlen', 'url': None},
 {'id': 1272770680,
  'slug': 'ai-fitness-alsfeld',
  'name': 'Ai Fitness Alsfeld',
  'city': 'Alsfeld',
  'url': 'https://www.ai-fitness.de/studios/alsfeld'},
 {'id': 1396233150,
  'slug': 'ai-fitness-ansbach',
  'name': 'Ai Fitness Ansbach',
  'city': 'Ansbach',
  'url': 'https://www.ai-fitness.de/studios/ansbach'},
 {'id': 1393391460,
  'slug': 'ai-fitness-augsburg-haunstetten',
  'name': 'Ai Fitness Augsburg-Haunstetten',
  'city': 'Augsburg-Haunstetten',
  'url': 'https://www.ai-fitness.de/studios/augsburg-haunstetten'},
 {'id': 1401356830,
  'slug': 'ai-fitness-augsburg-stadtbergen',
  'name': 'Ai Fitness Augsburg-Stadtbergen',
  'city': 'Augsburg-Stadtbergen',
  'url': 'https://www.ai-fitness.de/studios/augsburg-stadtbergen'},
 {'id': 1263720750,
  'slug': 'ai-fitness-bad-hersfeld',
  'name': 'Ai Fitness Bad Hersfeld',
  'city': 'Bad Hersfeld',
  'url': 'https://www.ai-fitness.de/studios/bad-hersfeld'},
 {'id': 1331091060,
  'slug': 'ai-fitness-bad-oeynhausen',
  'name': 'Ai Fitness Bad Oeynhausen',
  'city': 'Bad Oeynhausen',
  'url': 'https://www.ai-fitness.de/studios/badoeynhausen'},
 {'id': 1234787240,
  'slug': 'ai-fitness-bergisch-gladbach',
  'name': 'Ai Fitness Bergisch Gladbach',
  'city': 'Bergisch Gladbach',
  'url': 'https://www.ai-fitness.de/studios/bergisch-gladbach'},
 {'id': 2151367430,
  'slug': 'ai-fitness-berlin-moabit',
  'name': 'Ai Fitness Berlin - Moabit',
  'city': 'Berlin',
  'url': None},
 {'id': 2116921100,
  'slug': 'ai-fitness-bielefeld-brackwede',
  'name': 'Ai Fitness Bielefeld Brackwede',
  'city': 'Bielefeld',
  'url': None},
 {'id': 1321967250,
  'slug': 'ai-fitness-bielefeld-city',
  'name': 'Ai Fitness Bielefeld City',
  'city': 'Bielefeld',
  'url': 'https://www.ai-fitness.de/studios/bielefeld'},
 {'id': 1468963780,
  'slug': 'ai-fitness-bielefeld-schildesche',
  'name': 'Ai Fitness Bielefeld Schildesche',
  'city': 'Bielefeld',
  'url': None},
 {'id': 1316633090,
  'slug': 'ai-fitness-bielefeld-sieker',
  'name': 'Ai Fitness Bielefeld Sieker',
  'city': 'Bielefeld',
  'url': 'https://www.ai-fitness.de/studios/bielefeld-sieker'},
 {'id': 1270662880, 'slug': 'ai-fitness-bocholt', 'name': 'Ai Fitness Bocholt', 'city': 'Bocholt', 'url': None},
 {'id': 1274187050,
  'slug': 'ai-fitness-bochum',
  'name': 'Ai Fitness Bochum',
  'city': 'Bochum',
  'url': 'https://www.ai-fitness.de/studios/bochum'},
 {'id': 1239136210,
  'slug': 'ai-fitness-bonn',
  'name': 'Ai Fitness Bonn',
  'city': 'Bonn',
  'url': 'https://www.ai-fitness.de/studios/bonn'},
 {'id': 1468143780,
  'slug': 'ai-fitness-bonn-endenich',
  'name': 'Ai Fitness Bonn Endenich',
  'city': 'Bonn',
  'url': 'https://www.ai-fitness.de/studios/bonn-endenich'},
 {'id': 1273970690,
  'slug': 'ai-fitness-borken',
  'name': 'Ai Fitness Borken',
  'city': 'Borken',
  'url': 'https://www.ai-fitness.de/studios/borken'},
 {'id': 1274239870,
  'slug': 'ai-fitness-bottrop',
  'name': 'Ai Fitness Bottrop',
  'city': 'Bottrop',
  'url': 'https://www.ai-fitness.de/studios/bottrop'},
 {'id': 1798616320,
  'slug': 'ai-fitness-bremen-munte',
  'name': 'Ai Fitness Bremen Munte',
  'city': 'Bremen',
  'url': 'https://www.ai-fitness.de/studios/bremen-munte'},
 {'id': 1837895800,
  'slug': 'ai-fitness-bremen-vahr',
  'name': 'Ai Fitness Bremen Vahr',
  'city': 'Bremen',
  'url': 'https://www.ai-fitness.de/studios/bremen-vahr'},
 {'id': 1857802530,
  'slug': 'ai-fitness-brilon',
  'name': 'Ai Fitness Brilon',
  'city': 'Brilon',
  'url': 'https://www.ai-fitness.de/studios/brilon'},
 {'id': 1331272490,
  'slug': 'ai-fitness-bunde',
  'name': 'Ai Fitness Bünde',
  'city': 'Bünde',
  'url': 'https://www.ai-fitness.de/studios/buende'},
 {'id': 1288065730,
  'slug': 'ai-fitness-castrop-nord',
  'name': 'Ai Fitness Castrop Nord',
  'city': 'Castrop-Rauxel',
  'url': 'https://www.ai-fitness.de/studios/castrop-nord'},
 {'id': 1289827530,
  'slug': 'ai-fitness-castrop-rauxel',
  'name': 'Ai Fitness Castrop-Rauxel',
  'city': 'Castrop-Rauxel',
  'url': 'https://www.ai-fitness.de/studios/castrop-rauxel'},
 {'id': 1348846630,
  'slug': 'ai-fitness-celle-neuenhausen',
  'name': 'Ai Fitness Celle Neuenhäusen',
  'city': 'Celle',
  'url': 'https://www.ai-fitness.de/studios/celle'},
 {'id': 2026968340,
  'slug': 'ai-fitness-celle-telefunkenstrasse',
  'name': 'Ai Fitness Celle Telefunkenstrasse',
  'city': 'Celle',
  'url': 'https://www.ai-fitness.de/studios/celle-telefunkenstrasse'},
 {'id': 1412625590,
  'slug': 'ai-fitness-coburg',
  'name': 'Ai Fitness Coburg',
  'city': 'Coburg',
  'url': 'https://www.ai-fitness.de/studios/coburg'},
 {'id': 1420664670,
  'slug': 'ai-fitness-darmstadt',
  'name': 'Ai Fitness Darmstadt',
  'city': 'Darmstadt',
  'url': 'https://www.ai-fitness.de/studios/darmstadt'},
 {'id': 1834876890,
  'slug': 'ai-fitness-delmenhorst',
  'name': 'Ai Fitness Delmenhorst',
  'city': 'Delmenhorst',
  'url': 'https://www.ai-fitness.de/studios/delmenhorst'},
 {'id': 1349127220,
  'slug': 'ai-fitness-detmold',
  'name': 'Ai Fitness Detmold',
  'city': 'Detmold',
  'url': 'https://www.ai-fitness.de/studios/detmold'},
 {'id': 1617841590,
  'slug': 'ai-fitness-dietzenbach',
  'name': 'Ai Fitness Dietzenbach',
  'city': 'Dietzenbach',
  'url': 'https://www.ai-fitness.de/studios/dietzenbach'},
 {'id': 1302416220,
  'slug': 'ai-fitness-dortmund-lutgendortmund',
  'name': 'Ai Fitness Dortmund Lütgendortmund',
  'city': 'Dortmund',
  'url': 'https://www.ai-fitness.de/studios/dortmund-luetgendortmund'},
 {'id': 1310695370,
  'slug': 'ai-fitness-dortmund-city',
  'name': 'Ai Fitness Dortmund-City',
  'city': 'Dortmund',
  'url': 'https://www.ai-fitness.de/studios/dortmund-city'},
 {'id': 1302920060,
  'slug': 'ai-fitness-dortmund-dorstfeld',
  'name': 'Ai Fitness Dortmund-Dorstfeld',
  'city': 'Dortmund',
  'url': 'https://www.ai-fitness.de/studios/dortmund-dorstfeld'},
 {'id': 1434882720,
  'slug': 'ai-fitness-dreieich',
  'name': 'Ai Fitness Dreieich',
  'city': 'Dreieich',
  'url': 'https://www.ai-fitness.de/studios/dreieich'},
 {'id': 1281642530,
  'slug': 'ai-fitness-duisburg-city',
  'name': 'Ai Fitness Duisburg City',
  'city': 'Duisburg',
  'url': 'https://www.ai-fitness.de/studios/duisburg-city'},
 {'id': 1279902650,
  'slug': 'ai-fitness-duisburg-innenhafen',
  'name': 'Ai Fitness Duisburg Innenhafen',
  'city': 'Duisburg',
  'url': 'https://www.ai-fitness.de/studios/duisburg-innenhafen'},
 {'id': 1218401810,
  'slug': 'ai-fitness-duisburg-konigsgalerie',
  'name': 'Ai Fitness Duisburg Königsgalerie',
  'city': 'Duisburg',
  'url': 'https://fivestar-fitness.de/fitnessstudios/duisburg-koenigsgalerie'},
 {'id': 1221845900,
  'slug': 'ai-fitness-duisburg-meiderich',
  'name': 'Ai Fitness Duisburg Meiderich',
  'city': 'Duisburg',
  'url': 'https://www.ai-fitness.de/studios/duisburg-meiderich'},
 {'id': 1288551800,
  'slug': 'ai-fitness-dusseldorf-flingern',
  'name': 'Ai Fitness Düsseldorf Flingern',
  'city': 'Düsseldorf',
  'url': 'https://www.ai-fitness.de/studios/flingern'},
 {'id': 1288377920,
  'slug': 'ai-fitness-dusseldorf-oberbilk',
  'name': 'Ai Fitness Düsseldorf Oberbilk',
  'city': 'Düsseldorf',
  'url': 'https://www.ai-fitness.de/studios/oberbilk'},
 {'id': 2217389190,
  'slug': 'ai-fitness-erlangen-ost',
  'name': 'Ai Fitness Erlangen-Ost',
  'city': 'Erlangen',
  'url': 'https://www.ai-fitness.de/studios/erlangen-ost'},
 {'id': 1211494410,
  'slug': 'ai-fitness-essen-bergerhausen',
  'name': 'Ai Fitness Essen Bergerhausen',
  'city': 'Essen',
  'url': 'https://www.ai-fitness.de/studios/essen-bergerhausen'},
 {'id': 1222008710,
  'slug': 'ai-fitness-essen-kray',
  'name': 'Ai Fitness Essen Kray',
  'city': 'Essen',
  'url': 'https://www.ai-fitness.de/studios/essen-kray'},
 {'id': 1289379010,
  'slug': 'ai-fitness-essen-altenessen',
  'name': 'Ai Fitness Essen-Altenessen',
  'city': 'Essen',
  'url': 'https://www.ai-fitness.de/studios/altenessen'},
 {'id': 1289045240,
  'slug': 'ai-fitness-essen-borbeck',
  'name': 'Ai Fitness Essen-Borbeck',
  'city': 'Essen',
  'url': 'https://www.ai-fitness.de/studios/essen'},
 {'id': 1420850450,
  'slug': 'ai-fitness-esslingen',
  'name': 'Ai Fitness Esslingen',
  'city': 'Esslingen',
  'url': 'https://www.ai-fitness.de/studios/esslingen'},
 {'id': 1399187700,
  'slug': 'ai-fitness-freising',
  'name': 'Ai Fitness Freising',
  'city': 'Freising',
  'url': 'https://www.ai-fitness.de/studios/freising'},
 {'id': 1377860620,
  'slug': 'ai-fitness-friedrichshafen',
  'name': 'Ai Fitness Friedrichshafen',
  'city': 'Friedrichshafen',
  'url': 'https://www.ai-fitness.de/studios/friedrichshafen-bodenseecenter'},
 {'id': 1360175120,
  'slug': 'ai-fitness-friedrichshafen-flughafen',
  'name': 'Ai Fitness Friedrichshafen-Flughafen',
  'city': 'Friedrichshafen',
  'url': 'https://www.ai-fitness.de/studios/friedrichshafen'},
 {'id': 1397509340,
  'slug': 'ai-fitness-furth',
  'name': 'Ai Fitness Fürth',
  'city': 'Fürth',
  'url': 'https://www.ai-fitness.de/studios/fuerth'},
 {'id': 1297340400,
  'slug': 'ai-fitness-gelsenkirchen',
  'name': 'Ai Fitness Gelsenkirchen',
  'city': 'Gelsenkirchen',
  'url': 'https://www.ai-fitness.de/studios/gelsenkirchen'},
 {'id': 1938360680,
  'slug': 'ai-fitness-gummersbach',
  'name': 'Ai Fitness Gummersbach',
  'city': 'Gummersbach',
  'url': 'https://www.ai-fitness.de/studios/gummersbach'},
 {'id': 1421327860,
  'slug': 'ai-fitness-goppingen',
  'name': 'Ai Fitness Göppingen',
  'city': 'Göppingen',
  'url': 'https://www.ai-fitness.de/studios/goeppingen'},
 {'id': 2028400430,
  'slug': 'ai-fitness-gottingen-grone',
  'name': 'Ai Fitness Göttingen Grone',
  'city': 'Göttingen',
  'url': 'https://www.ai-fitness.de/studios/goettingen-grone'},
 {'id': 2020914540,
  'slug': 'ai-fitness-gottingen-weende',
  'name': 'Ai Fitness Göttingen Weende',
  'city': 'Göttingen',
  'url': 'https://www.ai-fitness.de/studios/goettingen-weende'},
 {'id': 1316568120,
  'slug': 'ai-fitness-gutersloh',
  'name': 'Ai Fitness Gütersloh',
  'city': 'Gütersloh',
  'url': 'https://www.ai-fitness.de/studios/guetersloh'},
 {'id': 1961342500,
  'slug': 'ai-fitness-gutersloh-kampstrasse',
  'name': 'Ai Fitness Gütersloh Kampstrasse',
  'city': 'Gütersloh',
  'url': 'https://www.ai-fitness.de/studios/guetersloh-kampstrasse'},
 {'id': 1288400590,
  'slug': 'ai-fitness-haan',
  'name': 'Ai Fitness Haan',
  'city': 'Haan',
  'url': 'https://www.ai-fitness.de/studios/haan'},
 {'id': 1306395220,
  'slug': 'ai-fitness-hagen-city',
  'name': 'Ai Fitness Hagen City',
  'city': 'Hagen',
  'url': 'https://www.ai-fitness.de/studios/hagen-city'},
 {'id': 1302635170,
  'slug': 'ai-fitness-hagen-markt',
  'name': 'Ai Fitness Hagen Markt',
  'city': 'Hagen',
  'url': 'https://www.ai-fitness.de/studios/hagen-markt'},
 {'id': 1614562350,
  'slug': 'ai-fitness-hainburg',
  'name': 'Ai Fitness Hainburg',
  'city': 'Hainburg',
  'url': 'https://www.ai-fitness.de/studios/hainburg'},
 {'id': 1273937040,
  'slug': 'ai-fitness-haltern',
  'name': 'Ai Fitness Haltern',
  'city': 'Haltern am See',
  'url': 'https://www.ai-fitness.de/studios/haltern'},
 {'id': 1316910130,
  'slug': 'ai-fitness-hamm',
  'name': 'Ai Fitness Hamm',
  'city': 'Hamm',
  'url': 'https://www.ai-fitness.de/studios/hamm'},
 {'id': 1434738230,
  'slug': 'ai-fitness-hanau',
  'name': 'Ai Fitness Hanau',
  'city': 'Hanau',
  'url': 'https://www.ai-fitness.de/studios/hanau'},
 {'id': 1348845010,
  'slug': 'ai-fitness-hannover',
  'name': 'Ai Fitness Hannover',
  'city': 'Hannover',
  'url': 'https://www.ai-fitness.de/studios/hannover'},
 {'id': 2028394920,
  'slug': 'ai-fitness-hannover-city',
  'name': 'Ai Fitness Hannover City',
  'city': 'Hannover',
  'url': 'https://www.ai-fitness.de/studios/hannover-city'},
 {'id': 2028514990,
  'slug': 'ai-fitness-hannover-misburg',
  'name': 'Ai Fitness Hannover Misburg',
  'city': 'Hannover',
  'url': 'https://www.ai-fitness.de/studios/hannover-misburg'},
 {'id': 2020896540,
  'slug': 'ai-fitness-hannover-hainholz',
  'name': 'Ai Fitness Hannover-Hainholz',
  'city': 'Hannover',
  'url': 'https://www.ai-fitness.de/studios/hannover-hainholz'},
 {'id': 1421775900,
  'slug': 'ai-fitness-heidenheim',
  'name': 'Ai Fitness Heidenheim',
  'city': 'Heidenheim',
  'url': 'https://www.ai-fitness.de/studios/heidenheim'},
 {'id': 1380854810,
  'slug': 'ai-fitness-heilbronn',
  'name': 'Ai Fitness Heilbronn',
  'city': 'Heilbronn',
  'url': 'https://www.ai-fitness.de/studios/heilbronn'},
 {'id': 1332939750,
  'slug': 'ai-fitness-herford-nord',
  'name': 'Ai Fitness Herford Nord',
  'city': 'Herford',
  'url': 'https://www.ai-fitness.de/studios/herfordnord'},
 {'id': 1331349750,
  'slug': 'ai-fitness-herford-sud',
  'name': 'Ai Fitness Herford Süd',
  'city': 'Herford',
  'url': 'https://www.ai-fitness.de/studios/herfordsued'},
 {'id': 1614877630,
  'slug': 'ai-fitness-heusenstamm',
  'name': 'Ai Fitness Heusenstamm',
  'city': 'Heusenstamm',
  'url': 'https://www.ai-fitness.de/studios/heusenstamm'},
 {'id': 1412397360,
  'slug': 'ai-fitness-hof',
  'name': 'Ai Fitness Hof',
  'city': 'Hof',
  'url': 'https://www.ai-fitness.de/studios/hof'},
 {'id': 1435828710,
  'slug': 'ai-fitness-homburg',
  'name': 'Ai Fitness Homburg',
  'city': 'Homburg',
  'url': 'https://www.ai-fitness.de/studios/homburg'},
 {'id': 1306255650,
  'slug': 'ai-fitness-iserlohn',
  'name': 'Ai Fitness Iserlohn',
  'city': 'Iserlohn',
  'url': 'https://www.ai-fitness.de/studios/iserlohn'},
 {'id': 1298421550,
  'slug': 'ai-fitness-julich',
  'name': 'Ai Fitness Jülich',
  'city': 'Jülich',
  'url': 'https://www.ai-fitness.de/studios/juelich'},
 {'id': 1437537730,
  'slug': 'ai-fitness-kaiserslautern',
  'name': 'Ai Fitness Kaiserslautern',
  'city': 'Kaiserslautern',
  'url': 'https://www.ai-fitness.de/studios/kaiserslautern'},
 {'id': 1878668730,
  'slug': 'ai-fitness-kaiserslautern-augustastr',
  'name': 'Ai Fitness Kaiserslautern Augustastr.',
  'city': 'Kaiserslautern',
  'url': 'https://www.ai-fitness.de/studios/kaiserslautern-augustastrasse'},
 {'id': 1210007090,
  'slug': 'ai-fitness-kamp-lintfort',
  'name': 'Ai Fitness Kamp-Lintfort',
  'city': 'Kamp-Lintfort',
  'url': 'https://www.ai-fitness.de/studios/kamp-lintfort'},
 {'id': 2028536650,
  'slug': 'ai-fitness-kassel-hollandische-str',
  'name': 'Ai Fitness Kassel Holländische Str.',
  'city': 'Kassel',
  'url': 'https://www.ai-fitness.de/studios/kassel-hollaendischestrasse'},
 {'id': 1363496420,
  'slug': 'ai-fitness-kassel-kurfurstengalerie',
  'name': 'Ai Fitness Kassel Kurfürstengalerie',
  'city': 'Kassel',
  'url': 'https://www.ai-fitness.de/studios/kassel'},
 {'id': 1432716880,
  'slug': 'ai-fitness-kirchheim-u-teck',
  'name': 'Ai Fitness Kirchheim u. Teck',
  'city': 'Kirchheim',
  'url': 'https://www.jumpers-fitness.com/studios/kirchheim-unter-teck'},
 {'id': 1245323690,
  'slug': 'ai-fitness-koblenz',
  'name': 'Ai Fitness Koblenz',
  'city': 'Koblenz',
  'url': 'https://www.ai-fitness.de/studios/koblenz'},
 {'id': 1317082920,
  'slug': 'ai-fitness-krefeld',
  'name': 'Ai Fitness Krefeld',
  'city': 'Krefeld',
  'url': 'https://www.ai-fitness.de/studios/krefeld'},
 {'id': 1459601490,
  'slug': 'ai-fitness-koln-agnesviertel',
  'name': 'Ai Fitness Köln Agnesviertel',
  'city': 'Köln',
  'url': 'https://www.ai-fitness.de/studios/koeln-agnesviertel'},
 {'id': 1458103500,
  'slug': 'ai-fitness-koln-hurth',
  'name': 'Ai Fitness Köln Hürth',
  'city': 'Hürth',
  'url': 'https://www.ai-fitness.de/studios/huerth'},
 {'id': 1459621830,
  'slug': 'ai-fitness-koln-lindenthal',
  'name': 'Ai Fitness Köln Lindenthal',
  'city': 'Köln',
  'url': 'https://www.ai-fitness.de/studios/koeln-lindenthal'},
 {'id': 1459298560,
  'slug': 'ai-fitness-koln-ossendorf',
  'name': 'Ai Fitness Köln Ossendorf',
  'city': 'Köln',
  'url': 'https://www.ai-fitness.de/studios/koeln-ossendorf'},
 {'id': 1458101250,
  'slug': 'ai-fitness-koln-poll',
  'name': 'Ai Fitness Köln Poll',
  'city': 'Köln',
  'url': 'https://www.ai-fitness.de/studios/koeln-poll'},
 {'id': 1459188740, 'slug': 'ai-fitness-koln-porz', 'name': 'Ai Fitness Köln Porz', 'city': 'Köln', 'url': 'https://www.ai-fitness.de/studios/koeln-porz'},
 {'id': 1459768080,
  'slug': 'ai-fitness-koln-sulz',
  'name': 'Ai Fitness Köln Sülz',
  'city': 'Köln',
  'url': 'https://www.ai-fitness.de/studios/koeln-suelz'},
 {'id': 2029268670, 'slug': 'ai-fitness-laatzen', 'name': 'Ai Fitness Laatzen', 'city': 'Laatzen', 'url': 'https://www.ai-fitness.de/studios/laatzen'},
 {'id': 1848327210, 'slug': 'ai-fitness-lahnstein', 'name': 'Ai Fitness Lahnstein', 'city': 'Lahnstein', 'url': 'https://www.ai-fitness.de/studios/lahnstein'},
 {'id': 1413241400,
  'slug': 'ai-fitness-lahr',
  'name': 'Ai Fitness Lahr',
  'city': 'Lahr',
  'url': 'https://www.ai-fitness.de/studios/lahr'},
 {'id': 1386856820,
  'slug': 'ai-fitness-landshut-kumhausen',
  'name': 'Ai Fitness Landshut-Kumhausen',
  'city': 'Kumhausen',
  'url': 'https://www.ai-fitness.de/studios/landshut'},
 {'id': 1434562480,
  'slug': 'ai-fitness-langen',
  'name': 'Ai Fitness Langen',
  'city': 'Langen',
  'url': 'https://www.ai-fitness.de/studios/langen'},
 {'id': 1347741110,
  'slug': 'ai-fitness-langenfeld-berghausen',
  'name': 'Ai Fitness Langenfeld Berghausen',
  'city': 'Langenfeld (Rheinland)',
  'url': 'https://www.ai-fitness.de/studios/langenfeld-berghausen'},
 {'id': 1218871150,
  'slug': 'ai-fitness-langenfeld-city',
  'name': 'Ai Fitness Langenfeld City',
  'city': 'Langenfeld',
  'url': 'https://www.ai-fitness.de/studios/langenfeld-berghausen'},
 {'id': 1614924150,
  'slug': 'ai-fitness-langenselbold',
  'name': 'Ai Fitness Langenselbold',
  'city': 'Langenselbold',
  'url': 'https://www.ai-fitness.de/studios/langenselbold'},
 {'id': 2151337610,
  'slug': 'ai-fitness-leipzig-sudvorstadt',
  'name': 'Ai Fitness Leipzig - Südvorstadt',
  'city': 'Leipzig',
  'url': 'https://www.ai-fitness.de/studios/leipzig-suedvorstadt'},
 {'id': 1460339600,
  'slug': 'ai-fitness-leverkusen',
  'name': 'Ai Fitness Leverkusen',
  'city': 'Leverkusen',
  'url': 'https://www.ai-fitness.de/studios/leverkusen'},
 {'id': 1317528250,
  'slug': 'ai-fitness-lippstadt',
  'name': 'Ai Fitness Lippstadt',
  'city': 'Lippstadt',
  'url': 'https://www.ai-fitness.de/studios/lippstadt'},
 {'id': 1361035670,
  'slug': 'ai-fitness-marburg',
  'name': 'Ai Fitness Marburg',
  'city': 'Marburg',
  'url': 'https://www.ai-fitness.de/studios/marburg'},
 {'id': 1891763530, 'slug': 'ai-fitness-melle', 'name': 'Ai Fitness Melle', 'city': 'Melle', 'url': 'https://www.ai-fitness.de/studios/melle'},
 {'id': 1302519100,
  'slug': 'ai-fitness-menden',
  'name': 'Ai Fitness Menden',
  'city': 'Menden',
  'url': 'https://www.ai-fitness.de/studios/menden'},
 {'id': 1349190720,
  'slug': 'ai-fitness-minden',
  'name': 'Ai Fitness Minden',
  'city': 'Minden',
  'url': 'https://www.ai-fitness.de/studios/minden'},
 {'id': 1298433040,
  'slug': 'ai-fitness-moers',
  'name': 'Ai Fitness Moers',
  'city': 'Moers',
  'url': 'https://www.ai-fitness.de/studios/moers'},
 {'id': 1380727230,
  'slug': 'ai-fitness-monheim',
  'name': 'Ai Fitness Monheim',
  'city': 'Monheim am Rhein',
  'url': 'https://www.ai-fitness.de/studios/monheim'},
 {'id': 1298548160,
  'slug': 'ai-fitness-monchengladbach',
  'name': 'Ai Fitness Mönchengladbach',
  'city': 'Mönchengladbach',
  'url': 'https://www.ai-fitness.de/studios/moenchengladbach'},
 {'id': 1299228790,
  'slug': 'ai-fitness-mulheim',
  'name': 'Ai Fitness Mülheim',
  'city': 'Mülheim',
  'url': 'https://www.ai-fitness.de/studios/muelheim'},
 {'id': 2117491670,
  'slug': 'ai-fitness-munchen-freiham',
  'name': 'Ai Fitness München - Freiham',
  'city': 'München',
  'url': 'https://www.ai-fitness.de/studios/muenchen-freiham'},
 {'id': 1381129950,
  'slug': 'ai-fitness-munchen-haar',
  'name': 'Ai Fitness München-Haar',
  'city': 'Haar (München)',
  'url': 'https://www.ai-fitness.de/studios/muenchen-haar'},
 {'id': 2151375320,
  'slug': 'ai-fitness-munchen-laim',
  'name': 'Ai Fitness München-Laim',
  'city': 'München',
  'url': 'https://www.ai-fitness.de/studios/muenchen-laim'},
 {'id': 2141638290,
  'slug': 'ai-fitness-munchen-schwabing',
  'name': 'Ai Fitness München-Schwabing',
  'city': 'München',
  'url': 'https://www.ai-fitness.de/studios/muenchen-schwabing'},
 {'id': 2151363640,
  'slug': 'ai-fitness-munchen-sendling',
  'name': 'Ai Fitness München-Sendling',
  'city': 'München',
  'url': 'https://www.ai-fitness.de/studios/muenchen-sendling'},
 {'id': 2141642020,
  'slug': 'ai-fitness-munchen-trudering',
  'name': 'Ai Fitness München-Trudering',
  'city': 'München',
  'url': 'https://www.ai-fitness.de/studios/muenchen-trudering'},
 {'id': 1380861940,
  'slug': 'ai-fitness-munchen-unterhaching',
  'name': 'Ai Fitness München-Unterhaching',
  'city': 'Unterhaching',
  'url': 'https://www.ai-fitness.de/studios/neumarkt/muenchen-unterhaching'},
 {'id': 1833633980, 'slug': 'ai-fitness-munster', 'name': 'Ai Fitness Münster', 'city': 'Münster', 'url': 'https://www.ai-fitness.de/studios/muenster'},
 {'id': 1411032740,
  'slug': 'ai-fitness-neumarkt',
  'name': 'Ai Fitness Neumarkt',
  'city': 'Neumarkt',
  'url': 'https://www.ai-fitness.de/studios/neumarkt'},
 {'id': 2020908920,
  'slug': 'ai-fitness-neustadt-am-rubenberge',
  'name': 'Ai Fitness Neustadt am Rübenberge',
  'city': 'Neustadt am Rübenberge',
  'url': 'https://www.ai-fitness.de/studios/neustadt-am-ruebenberge'},
 {'id': 1229990490,
  'slug': 'ai-fitness-neuwied',
  'name': 'Ai Fitness Neuwied',
  'city': 'Neuwied',
  'url': 'https://www.ai-fitness.de/studios/neuwied'},
 {'id': 1393391310,
  'slug': 'ai-fitness-nurnberg',
  'name': 'Ai Fitness Nürnberg',
  'city': 'Nürnberg',
  'url': 'https://www.ai-fitness.de/studios/nuernberg'},
 {'id': 2061859400,
  'slug': 'ai-fitness-nurnberg-eberhardshof',
  'name': 'Ai Fitness Nürnberg - Eberhardshof',
  'city': 'Nürnberg',
  'url': 'https://www.ai-fitness.de/studios/nuernberg-eberhardshof'},
 {'id': 1266244000,
  'slug': 'ai-fitness-oberhausen',
  'name': 'Ai Fitness Oberhausen',
  'city': 'Oberhausen',
  'url': 'https://www.ai-fitness.de/studios/oberhausen'},
 {'id': 1614560440,
  'slug': 'ai-fitness-obertshausen',
  'name': 'Ai Fitness Obertshausen',
  'city': 'Obertshausen',
  'url': 'https://www.ai-fitness.de/studios/obertshausen'},
 {'id': 1834868000,
  'slug': 'ai-fitness-oldenburg',
  'name': 'Ai Fitness Oldenburg',
  'city': 'Oldenburg',
  'url': 'https://www.ai-fitness.de/studios/oldenburg'},
 {'id': 1333086660,
  'slug': 'ai-fitness-osnabruck',
  'name': 'Ai Fitness Osnabrück',
  'city': 'Osnabrück',
  'url': 'https://www.ai-fitness.de/studios/osnabrueck'},
 {'id': 1941146020, 'slug': 'ai-fitness-paderborn', 'name': 'Ai Fitness Paderborn', 'city': 'Paderborn', 'url': 'https://www.ai-fitness.de/studios/paderborn'},
 {'id': 1387224580,
  'slug': 'ai-fitness-passau',
  'name': 'Ai Fitness Passau',
  'city': 'Passau',
  'url': 'https://www.ai-fitness.de/studios/passau'},
 {'id': 1457842740,
  'slug': 'ai-fitness-pulheim',
  'name': 'Ai Fitness Pulheim',
  'city': 'Pulheim',
  'url': 'https://www.ai-fitness.de/studios/pulheim'},
 {'id': 1386935580,
  'slug': 'ai-fitness-ravensburg',
  'name': 'Ai Fitness Ravensburg',
  'city': 'Ravensburg',
  'url': 'https://www.ai-fitness.de/studios/ravensburg'},
 {'id': 1333120210,
  'slug': 'ai-fitness-recklinghausen-city',
  'name': 'Ai Fitness Recklinghausen-City',
  'city': 'Recklinghausen',
  'url': 'https://www.ai-fitness.de/studios/recklinghausen-city'},
 {'id': 1332920560,
  'slug': 'ai-fitness-recklinghausen-hochlarmark',
  'name': 'Ai Fitness Recklinghausen-Hochlarmark',
  'city': 'Recklinghausen',
  'url': 'https://www.ai-fitness.de/studios/recklinghausen-hochlarmark'},
 {'id': 1411158080,
  'slug': 'ai-fitness-regensburg',
  'name': 'Ai Fitness Regensburg',
  'city': 'Regensburg',
  'url': 'https://www.ai-fitness.de/studios/regensburg'},
 {'id': 1424074880,
  'slug': 'ai-fitness-rosenheim-city',
  'name': 'Ai Fitness Rosenheim - City',
  'city': 'Rosenheim',
  'url': 'https://www.ai-fitness.de/studios/stuttgart-degerloch/rosenheim'},
 {'id': 1569014960,
  'slug': 'ai-fitness-rosenheim-aicherpark',
  'name': 'Ai Fitness Rosenheim Aicherpark',
  'city': 'Rosenheim',
  'url': 'https://www.ai-fitness.de/studios/rosenheim-aicherpark'},
 {'id': 1435224360,
  'slug': 'ai-fitness-saarlouis',
  'name': 'Ai Fitness Saarlouis',
  'city': 'Saarlouis',
  'url': 'https://www.ai-fitness.de/studios/saarlouis'},
 {'id': 1393295670,
  'slug': 'ai-fitness-schwabach',
  'name': 'Ai Fitness Schwabach',
  'city': 'Schwabach',
  'url': 'https://www.ai-fitness.de/studios/schwabach'},
 {'id': 1468131860, 'slug': 'ai-fitness-siegen', 'name': 'Ai Fitness Siegen', 'city': 'Siegen', 'url': 'https://www.ai-fitness.de/studios/siegen'},
 {'id': 1413941890,
  'slug': 'ai-fitness-sindelfingen',
  'name': 'Ai Fitness Sindelfingen',
  'city': 'Sindelfingen',
  'url': 'https://www.ai-fitness.de/studios/sindelfingen'},
 {'id': 1317518350,
  'slug': 'ai-fitness-soest',
  'name': 'Ai Fitness Soest',
  'city': 'Soest',
  'url': 'https://www.ai-fitness.de/studios/soest'},
 {'id': 2020902580,
  'slug': 'ai-fitness-springe',
  'name': 'Ai Fitness Springe',
  'city': 'Springe',
  'url': 'https://www.ai-fitness.de/studios/springe'},
 {'id': 1387060970,
  'slug': 'ai-fitness-straubing',
  'name': 'Ai Fitness Straubing',
  'city': 'Straubing',
  'url': 'https://www.ai-fitness.de/studios/straubing'},
 {'id': 1422734600,
  'slug': 'ai-fitness-stuttgart-degerloch',
  'name': 'Ai Fitness Stuttgart-Degerloch',
  'city': 'Stuttgart',
  'url': 'https://www.ai-fitness.de/studios/stuttgart-degerloch'},
 {'id': 1466815190,
  'slug': 'ai-fitness-tonisvorst',
  'name': 'Ai Fitness Tönisvorst',
  'city': 'Tönisvorst',
  'url': 'https://www.ai-fitness.de/studios/toenisvorst'},
 {'id': 1296826160,
  'slug': 'ai-fitness-unna',
  'name': 'Ai Fitness Unna',
  'city': 'Unna',
  'url': 'https://www.ai-fitness.de/studios/unna'},
 {'id': 1377760660,
  'slug': 'ai-fitness-volklingen',
  'name': 'Ai Fitness Völklingen',
  'city': 'Völklingen',
  'url': 'https://www.ai-fitness.de/studios/voelklingen'},
 {'id': 1296857860,
  'slug': 'ai-fitness-wanne-eickel',
  'name': 'Ai Fitness Wanne-Eickel',
  'city': 'Herne',
  'url': 'https://www.ai-fitness.de/studios/wanne-eickel'},
 {'id': 1411606360,
  'slug': 'ai-fitness-weiden',
  'name': 'Ai Fitness Weiden',
  'city': 'Weiden',
  'url': 'https://ww.ai-fitness.de/studios/weiden'},
 {'id': 1614595050,
  'slug': 'ai-fitness-weiskirchen',
  'name': 'Ai Fitness Weiskirchen',
  'city': 'Rodgau',
  'url': 'https://www.ai-fitness.de/studios/weiskirchen'},
 {'id': 1820691000, 'slug': 'ai-fitness-werne', 'name': 'Ai Fitness Werne', 'city': 'Werne', 'url': 'https://www.ai-fitness.de/studios/werne'},
 {'id': 1347697750,
  'slug': 'ai-fitness-wesel-city',
  'name': 'Ai Fitness Wesel City',
  'city': 'Wesel',
  'url': 'https://www.ai-fitness.de/studios/wesel'},
 {'id': 1377227830,
  'slug': 'ai-fitness-wesel-industriegebiet',
  'name': 'Ai Fitness Wesel Industriegebiet',
  'city': 'Wesel',
  'url': 'https://www.ai-fitness.de/studios/wesel-industriegebiet'},
 {'id': 1435011010,
  'slug': 'ai-fitness-wiesbaden',
  'name': 'Ai Fitness Wiesbaden',
  'city': 'Wiesbaden',
  'url': 'https://www.ai-fitness.de/studios/wiesbaden'},
 {'id': 1279759470,
  'slug': 'ai-fitness-wuppertal-elberfeld-gathe',
  'name': 'Ai Fitness Wuppertal Elberfeld Gathe',
  'city': 'Wuppertal',
  'url': 'https://www.ai-fitness.de/studios/elberfeld'},
 {'id': 1251458270,
  'slug': 'ai-fitness-wuppertal-elberfeld-neumarkt',
  'name': 'Ai Fitness Wuppertal Elberfeld Neumarkt',
  'city': 'Wuppertal',
  'url': 'https://www.ai-fitness.de/studios/wuppertal-neumarkt'},
 {'id': 1281492160,
  'slug': 'ai-fitness-wuppertal-barmen',
  'name': 'Ai Fitness Wuppertal-Barmen',
  'city': 'Wuppertal',
  'url': 'https://www.ai-fitness.de/studios/wuppertal'},
 {'id': 1438240210,
  'slug': 'ai-fitness-wurzburg',
  'name': 'Ai Fitness Würzburg',
  'city': 'Würzburg',
  'url': 'https://www.ai-fitness.de/studios/wuerzburg'}]

STUDIOS = [studio for studio in ALL_STUDIOS if studio["url"]]

